In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv("Absenteeism_preprocessed.csv")

In [3]:
data_preprocessed.describe(include = 'all')

,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Month,Day_of_Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
count,700,700,700,700,700.00000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.0,700.000000,700.000000,700.000000
unique,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,False,False,False,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,525,694,637,418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,6.36000,2.011429,222.347143,29.892857,36.417143,271.801774,26.737143,0.0,1.021429,0.687143,6.761429
std,NaN,NaN,NaN,NaN,3.50501,1.480396,66.312960,14.804446,6.379083,40.021804,4.254701,0.0,1.112215,1.166095,12.670082
min,NaN,NaN,NaN,NaN,1.00000,0.000000,118.000000,5.000000,27.000000,205.917000,19.000000,0.0,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,3.00000,1.000000,179.000000,16.000000,31.000000,241.476000,24.000000,0.0,0.000000,0.000000,2.000000
50%,NaN,NaN,NaN,NaN,6.00000,2.000000,225.000000,26.000000,37.000000,264.249000,25.000000,0.0,1.000000,0.000000,3.000000
75%,NaN,NaN,NaN,NaN,10.00000,3.000000,260.000000,50.000000,40.000000,294.217000,31.000000,0.0,2.000000,1.000000,8.000000


In [4]:
data_preprocessed.head()

,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Month,Day_of_Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,False,False,False,True,7,1,289,36,33,239.554,30,0,2,1,4
1,False,False,False,False,7,1,118,13,50,239.554,31,0,1,0,0
2,False,False,False,True,7,2,179,51,38,239.554,31,0,0,0,2
3,True,False,False,False,7,3,279,5,39,239.554,24,0,2,0,4
4,False,False,False,True,7,3,289,36,33,239.554,30,0,2,1,2


In [5]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [6]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [7]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [8]:
data_preprocessed['Excesive Absenteeism'] = targets

In [9]:
data_preprocessed.head()

,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Month,Day_of_Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Excesive Absenteeism
0,False,False,False,True,7,1,289,36,33,239.554,30,0,2,1,4,1
1,False,False,False,False,7,1,118,13,50,239.554,31,0,1,0,0,0
2,False,False,False,True,7,2,179,51,38,239.554,31,0,0,0,2,0
3,True,False,False,False,7,3,279,5,39,239.554,24,0,2,0,4,1
4,False,False,False,True,7,3,289,36,33,239.554,30,0,2,1,2,0


In [10]:
targets.sum()/targets.shape[0]

np.float64(0.45571428571428574)

In [11]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day_of_Week', 'Daily Work Load Average', 'Distance to Work',], axis = 1)

In [12]:
data_with_targets.head()

,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Month,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Excesive Absenteeism
0,False,False,False,True,7,289,33,30,0,2,1,1
1,False,False,False,False,7,118,50,31,0,1,0,0
2,False,False,False,True,7,179,38,31,0,0,0,0
3,True,False,False,False,7,279,39,24,0,2,0,1
4,False,False,False,True,7,289,33,30,0,2,1,0


In [13]:
data_with_targets is data_preprocessed

False

In [14]:
data_with_targets.iloc[:,:-1]

,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Month,Transportation Expense,Age,Body Mass Index,Education,Children,Pets
0,False,False,False,True,7,289,33,30,0,2,1
1,False,False,False,False,7,118,50,31,0,1,0
2,False,False,False,True,7,179,38,31,0,0,0
3,True,False,False,False,7,279,39,24,0,2,0
4,False,False,False,True,7,289,33,30,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...
695,True,False,False,False,5,179,40,22,0,2,0
696,True,False,False,False,5,225,28,24,0,1,2
697,True,False,False,False,5,330,28,25,0,0,0
698,False,False,False,True,5,235,32,25,0,0,0


In [15]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

### standardize our data

In [16]:
#from sklearn.preprocessing import StandardScaler
#absenteeism_scaler = StandardScaler()

In [17]:
# import the libraries needed to create the Custom Scaler
# note that all of them are a part of the sklearn package
# moreover, one of them is actually the StandardScaler module, 
# so you can imagine that the Custom Scaler is build on it

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy=copy, with_mean=with_mean, with_std=with_std)
        # with some columns 'twist'
        self.copy = copy
        self.with_mean = with_mean
        self.with_std = with_std
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns], axis=0)
        self.var_ = np.var(X[self.columns], axis=0)
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [18]:
unscaled_inputs.columns.values

array(['reason_type_1', 'reason_type_2', 'reason_type_3', 'reason_type_4',
       'Month', 'Transportation Expense', 'Age', 'Body Mass Index',
       'Education', 'Children', 'Pets'], dtype=object)

In [19]:
columns_to_scale = ['Month', 'Transportation Expense', 'Age',
       'Body Mass Index', 'Children', 'Pets']

In [20]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [21]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

In [22]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [23]:
scaled_inputs

,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Month,Transportation Expense,Age,Body Mass Index,Education,Children,Pets
0,False,False,False,True,0.182726,1.005844,-0.536062,0.767431,0,0.880469,0.268487
1,False,False,False,False,0.182726,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
2,False,False,False,True,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
3,True,False,False,False,0.182726,0.854936,0.405184,-0.643782,0,0.880469,-0.589690
4,False,False,False,True,0.182726,1.005844,-0.536062,0.767431,0,0.880469,0.268487
...,...,...,...,...,...,...,...,...,...,...,...
695,True,False,False,False,-0.388293,-0.654143,0.562059,-1.114186,0,0.880469,-0.589690
696,True,False,False,False,-0.388293,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663
697,True,False,False,False,-0.388293,1.624567,-1.320435,-0.408580,0,-0.919030,-0.589690
698,False,False,False,True,-0.388293,0.190942,-0.692937,-0.408580,0,-0.919030,-0.589690


In [24]:
scaled_inputs.shape

(700, 11)

### slit the data into training and testing

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
train_test_split(scaled_inputs, targets)

[     reason_type_1  reason_type_2  reason_type_3  reason_type_4     Month  \
 178           True          False          False          False -0.959313   
 271          False          False          False           True  0.753746   
 587           True          False          False          False -1.244823   
 86           False          False          False           True  1.324766   
 130          False          False           True          False -1.530333   
 ..             ...            ...            ...            ...       ...   
 165           True          False          False          False -0.959313   
 641          False          False          False           True -0.959313   
 192          False          False          False           True -0.673803   
 430          False          False          False           True -0.388293   
 474          False          False          False           True  0.182726   
 
      Transportation Expense       Age  Body Mass Index  Educa

In [27]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets,train_size = 0.8, random_state = 20)

In [28]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(560, 11) (560,)
(140, 11) (140,)


## Logistic Regression with Sklearn

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

## Train the model

In [30]:
reg = LogisticRegression()

In [31]:
reg.fit(x_train, y_train)

LogisticRegression()

In [32]:
reg.score(x_train, y_train)

0.7785714285714286

In [33]:
model_output = reg.predict(x_train)
model_output

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [34]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [35]:
model_output == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [36]:
np.sum(model_output == y_train)

np.int64(436)

In [37]:
y_train.shape[0]

560

In [38]:
np.sum(model_output == y_train)/y_train.shape[0]

np.float64(0.7785714285714286)

# finding the intercept and the coefficient

In [39]:
reg.intercept_

array([-1.69032199])

In [40]:
reg.coef_

array([[ 2.79957484,  0.91304005,  3.09125908,  0.85362484,  0.16418968,
         0.6012604 , -0.16717696,  0.30783491,  0.        ,  0.36473108,
        -0.2697601 ]])

In [41]:
unscaled_inputs.columns.values

array(['reason_type_1', 'reason_type_2', 'reason_type_3', 'reason_type_4',
       'Month', 'Transportation Expense', 'Age', 'Body Mass Index',
       'Education', 'Children', 'Pets'], dtype=object)

In [42]:
feature_names = unscaled_inputs.columns.values

In [43]:
summary_table = pd.DataFrame(columns=['feature_names'], data = feature_names)
summary_table['coefficients'] = np.transpose(reg.coef_)
summary_table

,feature_names,coefficients
0,reason_type_1,2.799575
1,reason_type_2,0.913040
2,reason_type_3,3.091259
3,reason_type_4,0.853625
4,Month,0.164190
5,Transportation Expense,0.601260
6,Age,-0.167177
7,Body Mass Index,0.307835
8,Education,0.000000
9,Children,0.364731


In [44]:
summary_table.index = summary_table.index + 1

In [45]:
summary_table.loc[0] = ['intercept', reg.intercept_[0]]

In [46]:
summary_table = summary_table.sort_index()
summary_table

,feature_names,coefficients
0,intercept,-1.690322
1,reason_type_1,2.799575
2,reason_type_2,0.913040
3,reason_type_3,3.091259
4,reason_type_4,0.853625
5,Month,0.164190
6,Transportation Expense,0.601260
7,Age,-0.167177
8,Body Mass Index,0.307835
9,Education,0.000000


# interpreting the coefficients

In [47]:
summary_table['odds_ratio'] = np.exp(summary_table.coefficients)

In [48]:
summary_table

,feature_names,coefficients,odds_ratio
0,intercept,-1.690322,0.184460
1,reason_type_1,2.799575,16.437657
2,reason_type_2,0.913040,2.491886
3,reason_type_3,3.091259,22.004766
4,reason_type_4,0.853625,2.348143
5,Month,0.164190,1.178438
6,Transportation Expense,0.601260,1.824417
7,Age,-0.167177,0.846050
8,Body Mass Index,0.307835,1.360476
9,Education,0.000000,1.000000


In [49]:
summary_table.sort_values('odds_ratio', ascending = False)

,feature_names,coefficients,odds_ratio
3,reason_type_3,3.091259,22.004766
1,reason_type_1,2.799575,16.437657
2,reason_type_2,0.913040,2.491886
4,reason_type_4,0.853625,2.348143
6,Transportation Expense,0.601260,1.824417
10,Children,0.364731,1.440127
8,Body Mass Index,0.307835,1.360476
5,Month,0.164190,1.178438
9,Education,0.000000,1.000000
7,Age,-0.167177,0.846050


### testing

In [50]:
reg.score(x_test, y_test)

0.75

In [53]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.71534448, 0.28465552],
       [0.59609394, 0.40390606],
       [0.42788316, 0.57211684],
       [0.78524649, 0.21475351],
       [0.08644793, 0.91355207],
       [0.34311501, 0.65688499],
       [0.30624628, 0.69375372],
       [0.13293204, 0.86706796],
       [0.79450288, 0.20549712],
       [0.75194182, 0.24805818],
       [0.49726505, 0.50273495],
       [0.23005601, 0.76994399],
       [0.07524016, 0.92475984],
       [0.69217496, 0.30782504],
       [0.32559666, 0.67440334],
       [0.51292061, 0.48707939],
       [0.55563097, 0.44436903],
       [0.54402847, 0.45597153],
       [0.41514668, 0.58485332],
       [0.05495753, 0.94504247],
       [0.70754838, 0.29245162],
       [0.78524649, 0.21475351],
       [0.43045433, 0.56954567],
       [0.43045433, 0.56954567],
       [0.26386362, 0.73613638],
       [0.75359817, 0.24640183],
       [0.51958066, 0.48041934],
       [0.84214497, 0.15785503],
       [0.21145959, 0.78854041],
       [0.78524649, 0.21475351],
       [0.

In [54]:
predicted_proba.shape

(140, 2)

In [55]:
predicted_proba[:,1]

array([0.28465552, 0.40390606, 0.57211684, 0.21475351, 0.91355207,
       0.65688499, 0.69375372, 0.86706796, 0.20549712, 0.24805818,
       0.50273495, 0.76994399, 0.92475984, 0.30782504, 0.67440334,
       0.48707939, 0.44436903, 0.45597153, 0.58485332, 0.94504247,
       0.29245162, 0.21475351, 0.56954567, 0.56954567, 0.73613638,
       0.24640183, 0.48041934, 0.15785503, 0.78854041, 0.21475351,
       0.35968604, 0.66539297, 0.67769495, 0.52614999, 0.21475351,
       0.5345093 , 0.21325647, 0.72240522, 0.41038963, 0.60153094,
       0.20695402, 0.47418613, 0.22940902, 0.39131769, 0.83008111,
       0.54900709, 0.68102693, 0.28465552, 0.20644521, 0.19936588,
       0.60164123, 0.35958305, 0.65688499, 0.25631301, 0.82588421,
       0.42666761, 0.87732161, 0.22542401, 0.34143918, 0.35205702,
       0.72596553, 0.64624302, 0.28778049, 0.77909013, 0.2038162 ,
       0.26595562, 0.08037943, 0.21325647, 0.70912676, 0.3491458 ,
       0.21325647, 0.27258451, 0.90748623, 0.46805208, 0.60336

### save the model

In [56]:
import pickle

In [57]:
with open('model', 'wb') as file:
    pickle.dump(reg,file)

In [59]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)